// Code generated by entc, DO NOT EDIT.

package session

const (
	// Label holds the string label denoting the session type in the database.
	Label = "session"
	// FieldID holds the string denoting the id field in the database.
	FieldID        = "id"         // FieldSessionID holds the string denoting the session_id vertex property in the database.
	FieldSessionID = "session_id" // FieldBalance holds the string denoting the balance vertex property in the database.
	FieldBalance   = "balance"    // FieldGame holds the string denoting the game vertex property in the database.
	FieldGame      = "game"       // FieldCreatedAt holds the string denoting the created_at vertex property in the database.
	FieldCreatedAt = "created_at"

	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"

	// Table holds the table name of the session in the database.
	Table = "sessions"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "sessions"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_sessions"
)

// Columns holds all SQL columns for session fields.
var Columns = []string{
	FieldID,
	FieldSessionID,
	FieldBalance,
	FieldGame,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Session type.
var ForeignKeys = []string{
	"user_sessions",
}
