// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"ent-playground/ent/session"
	"ent-playground/ent/user"
	"errors"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// SessionCreate is the builder for creating a Session entity.
type SessionCreate struct {
	config
	mutation *SessionMutation
	hooks    []Hook
}

// SetSessionID sets the session_id field.
func (sc *SessionCreate) SetSessionID(i int64) *SessionCreate {
	sc.mutation.SetSessionID(i)
	return sc
}

// SetBalance sets the balance field.
func (sc *SessionCreate) SetBalance(i int64) *SessionCreate {
	sc.mutation.SetBalance(i)
	return sc
}

// SetGame sets the game field.
func (sc *SessionCreate) SetGame(s string) *SessionCreate {
	sc.mutation.SetGame(s)
	return sc
}

// SetNillableGame sets the game field if the given value is not nil.
func (sc *SessionCreate) SetNillableGame(s *string) *SessionCreate {
	if s != nil {
		sc.SetGame(*s)
	}
	return sc
}

// SetCreatedAt sets the created_at field.
func (sc *SessionCreate) SetCreatedAt(t time.Time) *SessionCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetUserID sets the user edge to User by id.
func (sc *SessionCreate) SetUserID(id string) *SessionCreate {
	sc.mutation.SetUserID(id)
	return sc
}

// SetUser sets the user edge to User.
func (sc *SessionCreate) SetUser(u *User) *SessionCreate {
	return sc.SetUserID(u.ID)
}

// Save creates the Session in the database.
func (sc *SessionCreate) Save(ctx context.Context) (*Session, error) {
	if _, ok := sc.mutation.SessionID(); !ok {
		return nil, errors.New("ent: missing required field \"session_id\"")
	}
	if _, ok := sc.mutation.Balance(); !ok {
		return nil, errors.New("ent: missing required field \"balance\"")
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return nil, errors.New("ent: missing required field \"created_at\"")
	}
	if _, ok := sc.mutation.UserID(); !ok {
		return nil, errors.New("ent: missing required edge \"user\"")
	}
	var (
		err  error
		node *Session
	)
	if len(sc.hooks) == 0 {
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SessionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sc.mutation = mutation
			node, err = sc.sqlSave(ctx)
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			mut = sc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SessionCreate) SaveX(ctx context.Context) *Session {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sc *SessionCreate) sqlSave(ctx context.Context) (*Session, error) {
	var (
		s     = &Session{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: session.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: session.FieldID,
			},
		}
	)
	if value, ok := sc.mutation.SessionID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: session.FieldSessionID,
		})
		s.SessionID = value
	}
	if value, ok := sc.mutation.Balance(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: session.FieldBalance,
		})
		s.Balance = value
	}
	if value, ok := sc.mutation.Game(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: session.FieldGame,
		})
		s.Game = &value
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: session.FieldCreatedAt,
		})
		s.CreatedAt = value
	}
	if nodes := sc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   session.UserTable,
			Columns: []string{session.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	s.ID = int(id)
	return s, nil
}
